[[constraint]]
  branch = "v2"
  name = "github.com/coreos/go-oidc"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "8.0.0"

[[override]]
  name = "github.com/imdario/mergo"
  revision = "6633656539c1639d9d78127b7d47c622b5d7b6dc"

[prune]
  go-tests = true
  unused-packages = true

